### ISSUE TITLE
Remote Icon is not removable from Tile

### ISSUE THREAD

**Issue by plains203** [austinscreations/OXRS-AC-TP32-ESP-FW#20] opened 2022-07-16 07:26 UTC
The remote tile has a burnt in icon that can't be removed. I think the code at fault is in this block.

`
// initialise the tile_style_LUT
void initStyleLut(void)
{
  styleLut[TS_NONE] = {TS_NONE, "", NULL};
  styleLut[TS_BUTTON] = {TS_BUTTON, "button", NULL};
  styleLut[TS_BUTTON_LEVEL_UP] = {TS_BUTTON_LEVEL_UP, "buttonLevelUp", NULL};
  styleLut[TS_BUTTON_LEVEL_DOWN] = {TS_BUTTON_LEVEL_DOWN, "buttonLevelDown", NULL};
  styleLut[TS_BUTTON_UP_DOWN] = {TS_BUTTON_UP_DOWN, "buttonUpDown", NULL};
  styleLut[TS_BUTTON_LEFT_RIGHT] = {TS_BUTTON_LEFT_RIGHT, "buttonLeftRight", NULL};
  styleLut[TS_BUTTON_PREV_NEXT] = {TS_BUTTON_PREV_NEXT, "buttonPrevNext", NULL};
  styleLut[TS_INDICATOR] = {TS_INDICATOR, "indicator", NULL};
  styleLut[TS_COLOR_PICKER] = {TS_COLOR_PICKER, "colorPicker", NULL};
  styleLut[TS_DROPDOWN] = {TS_DROPDOWN, "dropDown", NULL};
  styleLut[TS_KEYPAD] = {TS_KEYPAD, "keyPad", NULL};
  styleLut[TS_KEYPAD_BLOCKING] = {TS_KEYPAD_BLOCKING, "keyPadBlocking", NULL};
  styleLut[TS_REMOTE] = {TS_REMOTE, "remote", imgRemote};
  styleLut[TS_LINK] = {TS_LINK, "link", NULL};
}

`

**Comment by plains203** [comment] 2022-07-16 07:42
Confirmed by changing 
`
styleLut[TS_REMOTE] = {TS_REMOTE, "remote", imgRemote};
`
to 
`
styleLut[TS_REMOTE] = {TS_REMOTE, "remote", NULL};
`

**Comment by moinmoin-sh** [comment] 2022-07-16 07:46
Thanks James. The remote is the only one where I have the default icon. Think I'll scrap that idea in general. Turned out to be obsolete with all the other options we have now.

**Comment by moinmoin-sh** [comment] 2022-07-16 09:18
For compleness and reproduction:
could you please add information how you tried to remove the icon
Thanks

**Comment by plains203** [comment] 2022-07-16 09:45
I changed this block
```

**Comment by moinmoin-sh** [comment] 2022-07-16 10:29
Thanks James, I did fully understand how you would solve the issue. 
My question wasn't clear. I wanted to understand what you did to suppress the default icon **before** you made the change. I think I can answer my question by my own now. I assume you selected no icon when creating the remote tile which should result in having none displayed, but that didn't happen due to the default that I had in place.

**Comment by plains203** [comment] 2022-07-16 10:34
Sorry!
Yes I set no icon in the Admin UI, then I also tried to push a cmnd with no icon:"" to that tile and the icon remained.

**Comment by moinmoin-sh** [comment] 2022-07-16 16:15
fixed by #22

**Closed by moinmoin-sh** 2022-07-16 16:15 UTC
